### PR TITLE
Remove accounts module, hdkey dep, 'getKeyPair'.

### PR DESCRIPTION
**Pull request by jtobin**
hdkey is not used by the library proper, but the getKeyPair function takes a hdkey object as an argument (in the same way that various functions accept a web3 object) and so technically should be specified as a peer dependency.  This PR just corrects that oversight.

(See #88 for related discussion.)

### CODE REVIEW

**Comment by Fang-** [comment]
Isn't the proper fix here to just... not expose `getKeyPair`? I'm unsure why we even have that here, aside from it being used in tests.

**Comment by jtobin** [comment]
Yeah that's, uh, a good point.  Considering accounts.js hasn't been touched since September 23, 2018, I'm guessing it's just in there as a legacy quirk.  +1 to axing it altogether.

**Comment by jtobin** [comment]
@Fang- I took the liberty of pruning it, feel free to merge if you so desire!

**Review by Fang- — APPROVED** [review]
Clean!

**Pull request merged**
