### PR TITLE
Broader support for latest contracts

### PR DESCRIPTION
**Pull request by Fang-**
* Account for recent contract changes,
* Implements support for the star release contracts, [Linear](https://github.com/urbit/constitution/blob/master/contracts/LinearStarRelease.sol) and [Conditional](https://github.com/urbit/constitution/blob/master/contracts/ConditionalStarRelease.sol).

There are no tests for the release contracts yet. This is probably gonna be a pain in the ass so I need to think about how to do this properly. Putting this PR up in the mean time so it can start getting reviewed, and used by Bridge whenever it starts being needed.

### CODE REVIEW

**Comment by jtobin** [comment]
:+1: :+1: LGTM.  Hulking it!

One thing I had previously thought about re: testing is that it would be good to break the tests up a bit and make them each rely less on previous state.  This is somewhat annoying since the underlying chain state is persistent, of course, but still -- we could just use more addresses/ships, say, rather than keep using the same addresses, and relying so much on what we previously did with them way down in the test suite.

Another thing that I thought of previously was that it might be nice down the line is to replace the `{ error: true }; if (predicate) { error: false, reason: foo }` pattern with an error type like that found in `data.either`.  I've used `data.maybe` a bit and it's great, as far as a maybe type in JS goes. 😄 

(Neither comment relevant to this PR, just general thoughts I'd previously had.)

**Comment by Fang-** [comment]
We could definitely to with improving the testing method here in general. Let's sit down today (invite sent!) and see if we can come up with something that's not a gigantic pain.

**Comment by Fang-** [comment]
Something else I'm not quite pleased with in this PR is the naming of the check functions for these contracts? Their functions have identical names, but different logic, and checks.js doesn't currently namespace. Do we want to make it namespaced (ie `checks.constitution.canSpawn` rather than `checks.canSpawn`), or are we fine with weird function names?

*adds another point to the scoreboard for keeping checks separated by contract*

**Comment by Fang-** [comment]
I tried implementing tests for the newly supported contracts, but I can't even get a new tests file to run properly. To save my sanity I'm going to punt on this and continue work on transaction generation instead, which is higher priority anyway.

**Comment by jtobin** [comment]
@Fang- Do you want to merge this bad boy?  I got the tests working with HEAD on constitution, which is good enough for me for the time being. 😁

**Comment by Fang-** [comment]
I'm fine with merging this as-is, without the lockup contract tests. Not to make light of the importance of these pieces of software, but this particular part is definitely difficult to mess up. If it works, it works. Writing the remaining tests here is so far down my queue that we'd be waiting another month on it, so let's just merge.

**Pull request merged**
