### PR TITLE
bump ethereumjs-util to ^0.7.0.7

### PR DESCRIPTION
**Pull request by ghost**
This should hopefully fix some weird versions issues some people are having with ethereumjs versions. It might be a good idea to update bridge with the latest version installed after this goes to npm to update package-lock

### CODE REVIEW

**Review by jtobin — APPROVED** [review]
:+1: I'll cut a release now that includes the latest stuff.

**Comment by Fang-** [comment]
Wait hang on, I have questions about this wrt [comment here](https://groups.google.com/a/urbit.org/g/dev/c/XEIBEvCGe14/m/RZXOXGtDCgAJ). Still testing/seeing what's up!

**Comment by jtobin** [comment]
Oh sorry, by all means!

**Comment by Fang-** [comment]
I had thought that as of [6.2.0](https://github.com/ethereumjs/ethereumjs-util/releases/tag/v6.2.0) ethereumjs-util had changed their library structure, but I missed the part where they say:

> All functionality is additionally exposed through an aggregating `index.js` file, so this version remains backwards-compatible.

So apparently my concern was unwarranted and doing the update by itself is totally fine. I thought it might still be worth updating the few calls to the library we make (`isValidPrivate`, `privateToAddress`, `toChecksumAddress`, `isZeroAddress`) to use their new structure, but that doesn't work. Printing out the `Object.keys` of `utils`, I don't see the new-structure ones in there, either, even after doing a full re-install of the node-modules.

So, not sure what's up with that! We have other dependencies that are still pinned to the old version of ethereumjs-utils, maybe that's messing things up.

Including this seems fine, but it's also not clear to me it actually helps anything...

**Pull request merged**
