### PR TITLE
Upgraded dependencies and fixed tests

### LINKED ISSUE #62: #spawn tests fail on newer web3 versions
Most of our deps are specified in the `^x.y.z` format, which allows npm to upgrade to any semver-compatible version at its leisure.  It looks like some dependency breaks subtly on upgrade, though, since the `generates usable transaction` test fails with a length of 255 instead of the expected 253.

I discovered this while doing a plain `npm install` to update dependencies.  I wasn't in the mood to figure out exactly what caused the problem, though, so until I am, I've just manually knocked the dependencies back to what's specified by a working lockfile.

### LINKED ISSUE #79: web3 1.0.0-beta.54 does not build anymore on new versions of node
On never version of node (>10), the web3 dependency does not build anymore because scrypt depends on node-gyp, which is not supported anymore.

Using azimuth-js in a project or even cloning this repo and doing `npm install` gives the following error:
```
> scrypt@6.0.3 install /home/me/dev/azimuth-js/node_modules/scrypt
> node-gyp rebuild

make: Entering directory '/home/me/dev/azimuth-js/node_modules/scrypt/build'
  SOLINK_MODULE(target) Release/obj.target/copied_files.node
  COPY Release/copied_files.node
  CC(target) Release/obj.target/scrypt_wrapper/src/util/memlimit.o
<....>
  CC(target) Release/obj.target/scrypt_lib/scrypt/scrypt-1.2.0/libcperciva/alg/sha256.o
  CC(target) Release/obj.target/scrypt_lib/scrypt/scrypt-1.2.0/libcperciva/util/insecure_memzero.o
  CC(target) Release/obj.target/scrypt_lib/scrypt/scrypt-1.2.0/lib/scryptenc/scryptenc_cpuperf.o
  AR(target) Release/obj.target/scrypt_lib.a
  COPY Release/scrypt_lib.a
  CXX(target) Release/obj.target/scrypt/src/node-boilerplate/scrypt_common.o
  CXX(target) Release/obj.target/scrypt/src/node-boilerplate/scrypt_params_async.o
In file included from ../src/node-boilerplate/inc/scrypt_async.h:28,
                 from ../src/node-boilerplate/inc/scrypt_params_async.h:28,
                 from ../src/node-boilerplate/scrypt_params_async.cc:4:
../src/node-boilerplate/inc/scrypt_common.h: In constructor ‘NodeScrypt::Params::Params(const v8::Local<v8::Object>&)’:
../src/node-boilerplate/inc/scrypt_common.h:39:48: error: no matching function for call to ‘v8::Object::Get(v8::Local<v8::String>)’
   39 |       N(obj->Get(Nan::New("N").ToLocalChecked())->Uint32Value()),
```

This is a know issue, See for example: https://github.com/axic/scrypt.js/issues/5

Updating web3 should fix this. Is there a reason we are still on 1.0.0-beta.54?

### PR DESCRIPTION
**Pull request by lukebuehler**
This updates the npm packages to the latest versions where possible, but updates web3 only to the same version as bridge and azimuth-solidity. This should close #79. However, I only got it to build/install reliably on node versions up to 14; above that, I run into the same solidity build issues that are [described here](https://github.com/ransonhobbes/stardust/issues/12). 

I also fixed two of the spawn functions that had issues. Which closes #62 and #80. There is a strange problem where some web3 versions convert the contract return values to an array of string, and other versions to an array of int. The mapping call that I added should work in both cases.

### CODE REVIEW

**Comment by lukebuehler** [comment]
I forgot to mention, this single test case fails: https://github.com/urbit/azimuth-js/blob/ffce3c9fa3b5d148057ca6a34f918dcecebba606/test/test.js#L480.

But when you dig deeper there is this this comment which indicates that there is still an issue with the underlying function: https://github.com/urbit/azimuth-js/blob/ffce3c9fa3b5d148057ca6a34f918dcecebba606/check.js#L478

**Comment by Fang-** [comment]
This looks straightforward enough to me! @jtobin can you comment on the comparison there? I guess that should be a `web3.util` address equivalence check?

**Comment by jtobin** [comment]
@Fang- yeah it must be?  I can't see what else I would have been complaining about there.  Does the test pass if that comparison is done properly?

**Comment by lukebuehler** [comment]
Ah, the problem was that `eclipticAbi` was not available anymore via contracts.js, which was a change that was introduced in the previous PR by someone else, it was replaced by `newEcliptic.` Anyhow, the `canStartUpgradePoll` function is fixed now.

All tests are now building and this should be ready for merging.

**Review by Fang- — APPROVED** [review]
Very good! Thank you so much. (:

**Pull request merged**
